- Tyr-himinn/files/Tyr himinn/cinnamon/cinnamon.css
still throws an error _st_create_shadow_material that I have not been able to track down
OSD popups look OK, but would be preferable if they use the nice
border-images available in this theme, but I've bounced off
this, for now at least.
> Tyr-himinn: Get functional with 3.2 features

- Tyr-jord/files/Tyr jord/cinnamon/cinnamon.css
ensure sensible vertical panel applet spacing
ensure OSD popups match themeing
Suppress a couple of warning messages
still throws _st_create_shadow_material warnings
> Tyr-jord: Reinstate themed menu in 3.2

- ChromeOS/files/Chrome OS/cinnamon/cinnamon.css
More work is needed to make this look right in a vertical panel, and popup menus are coming up transparent as well, regardless of panel orientation.  There are some design choices that may need to be made to look right in a vertical panel, so corrections beyond this modest one here should be referred back to the original author, if contactable, IMO
> ChromeOS: Ensure applet spacing is sensible in a vertical panel

- Faience/files/Faience+/cinnamon/cinnamon.css
Ensure vertical applet spacing/positioning is sensible
Theme a couple of OSD popups to match existing OSD popup
Sort a few error messages because of missing CSS elements
NB I had to guess the menu background from the calendar popup, as the existing screen shapshot did not show the menu
so if someone has this theme on an earlier version of cinnamon and can confirm the menu looks right
that would be appreciated
> Faience+: Restore menu theming for 3.2

- Glass-Ubuntu-Classic/files/Glass Ubuntu Classic/cinnamon/cinnamon.css
Set applet-box spacing sensibly in a vertical panel
Suppress a couple of warning messages
> Glass-Ubuntu-Classic: Restore menu theming in 3.2

- Windows-10/files/Windows 10/cinnamon/cinnamon.css
Ensures sensible spacing and central alignment in a vertical panel
Windows-10: suppress warning messages from popup-separator-menu-item
> Windows-10: Add vertical styling for applet-box

- Jet-Gray/files/Jet-Gray/cinnamon/cinnamon.css
Add suitable vertical alignment/spacing in a vertical panel
Suppress warning messages from popup-separator-menu-item
Add additional themed OSD
> Jet-Gray: Correct menu theming in 3.2

- ChromeOS/files/Chrome OS/cinnamon/cinnamon.css
Put some shadow on (white) OSD popups so they look sensible against a white background
> ChromeOS:  Ensure context menu shows with a background

- Mint-XP/files/Mint-XP/cinnamon/cinnamon.css
Permits the panel to be highlighted correctly in the panel settings
@fmcgorenc - trust OK as per our earlier communications.  I'll be suggesting the same change to your other themes too
> Mint-XP: add panel highlight

- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/cinnamon.css
This permits the panel settings to highlight the panel the user is on successfully.
@edoz90 I made the change direct to the .css as I could not work out your build mechanism.  You might
like to add some build instructions to your github site.  If you are happy with this as it is I will merge, and assume you will adjust your own source code to avoid it getting over-written with your next change.
> Numix-Cinnamon-Transparent: Add panel highlight

- Photocopy/files/Photocopy/cinnamon/cinnamon.css
using text shadow in either of two places seems to use the previous category text as well
> Photocopy: fix doubled up menu text bug

- Carta/files/Carta/cinnamon/cinnamon.css
Remove separate panel shadow for top/bottom side to fix  linuxmint/cinnamon-spices-themes#189.
.
> Remove separate panel shadow for top/bottom side

- Carta/files/Carta/cinnamon/cinnamon.css
Fix for linuxmint/cinnamon-spices-themes#192: spacing for applet-box of top/bottom panel.
See also: ac43b6fbed41dd0df427d0a4a48a49627334bfc0
> Fix spacing for applet-box (top/bottom panel)

- Eleganse-dark/files/Eleganse-dark/cinnamon/cinnamon.css
According to theme comments, switcher has visibility issues on dark backgrounds. Adding light border for selected switcher item box for better visibility.
> Eleganse-dark: Border for switcher selected item

- Discreet-Flat/info.json
@getkey
The non existent description is forcing the website to say "Invalid Description".
This just adds a blank key to prevent that.
> Discreet-Flat: added empty description

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE
- .github/LICENSES/AGPL-3.0
- .github/LICENSES/Apache-2.0
- .github/LICENSES/CC0-1.0
- .github/LICENSES/GPL-2.0
- .github/LICENSES/GPL-3.0
- .github/LICENSES/LGPL-2.1
- .github/LICENSES/LGPL-3.0
- .github/LICENSES/MIT
- .github/LICENSES/README.md
Integrates ISSUE_TEMPLATE, CONTRIBUTING.md, and LICENSES info that applets/desklets/extensions use via the .github/ directory.
Probably should be merged when PR https://github.com/linuxmint/cinnamon-spices-themes/pull/207 is merged since ISSUE_TEMPLATE suggests using CODEOWNERS to get author names.
> ISSUE_TEMPLATE, CONTRIBUTING, LICENSES integration

- Carta/files/Carta/cinnamon/cinnamon.css
Bug:
- The default clock is not centered horizontally when the panel is vertical (i.e. when the panel is docked to the left or right sides of the screen).
Changes:
- Removed applet label's fixed width (originally fixed to be as wide as the panel itself) so that the clock text can be centered.
- Added min and max widths so that the clock text will not expand beyond the panel width.
> Carta: Center clock in side panels

- Spider-Void/files/Spider-Void/cinnamon/cinnamon.css
Minimal adaptation, reuse the menu layout for the window list preview.  Mis-spelt commit message, should be spider-void of course.
> Spider-Void: adapt for Cinnamon 3.8

- Thunderbolt/files/Thunderbolt/cinnamon/cinnamon.css
This update solves problem: popmenu cause a slight resizing if an active item is selected (#312)
> Thunderbolt: Update cinnamon.css

- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/gtk-3.0/thumbnail.png
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/gtk-3.20/thumbnail.png
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/gtk-3.22/thumbnail.png
- Adapta-Nokto/files/Adapta-Nokto/gtk-3.0/thumbnail.png
- Adapta-Nokto/files/Adapta-Nokto/gtk-3.20/thumbnail.png
- Adapta-Nokto/files/Adapta-Nokto/gtk-3.22/thumbnail.png
Correcting the symbolic links to use the dark GTK thumbnail.png for the Nokto variants.
> Adapta-Nokto and Adapta-Nokto-Eta - use correct GTK thumbnail.png

- Carta/files/Carta/cinnamon/cinnamon.css
Fix styles of windows-list progress and preview tiles ("broken" in new cinnamon version).
> Carta: fix windows-list progress and preview

- Adapta/README.md
@smurphos - I installed this theme (Adapta) with the built in theme manager on Linux Mint 18.3. Even after creating the symlink with the following the issue remained.
```sh
sudo ln -s ~/.themes/* /usr/share/themes/
```
The `README.me` file contains a broken path to the script `firefox_fix.sh`. I've corrected it by by removing `cinnamon/` from line [#67](https://github.com/linuxmint/cinnamon-spices-themes/blame/master/Adapta/README.md#L67).
```sh
chmod +x ~/.themes/Adapta/firefox_fix.sh && ~/.themes/Adapta/cinnamon/firefox_fix.sh
chmod +x ~/.themes/Adapta/firefox_fix.sh && ~/.themes/Adapta/firefox_fix.sh
```
Fixes #456
> Adapta: Issue #456

- Graphite-One/files/Graphite-One/cinnamon/cinnamon.css
- Graphite-Zero/files/Graphite-Zero/cinnamon/cinnamon.css
if Cinnamon pr 8096 gets pulled then the surrounding menu box around thumbnail boxes will be made to vanish, makes more efficient use of screen real estate.  Has no effect with the current code.
> Graphite: make thumbnail box disappear if code permits

- Adapta-Eta/README.md
- Adapta-Eta/files/Adapta-Eta/README.md
- Adapta-Eta/files/Adapta-Eta/cinnamon/cinnamon.css
- Adapta-Nokto-Eta/README.md
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/README.md
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/cinnamon/cinnamon.css
- Adapta-Nokto/README.md
- Adapta-Nokto/files/Adapta-Nokto/README.md
- Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
- Adapta/README.md
- Adapta/files/Adapta/README.md
- Adapta/files/Adapta/cinnamon/cinnamon.css
* Cinnamon - fix keyboard applet in vertical panel
* Cinnamon - remove weird margin on Media-Keys OSD that was pushing it down and right
* Cinnamon4 - menu - add a little spacing between the favorites-scrollbox and system-buttons
* Cinnamon - reduce horizontal padding on cinnamenu right-click context menu to match other popup menus
Closes #546
> Adapta update 120119

- Photocopy/files/Photocopy/cinnamon/cinnamon.css
- SimpleDock/files/SimpleDock/cinnamon/cinnamon.css
when in menu-selected-app-box in particular it slows the menu down
> Reduce use of text shadow in a couple of themes

- Adapta-Eta/README.md
- Adapta-Eta/files/Adapta-Eta/README.md
- Adapta-Eta/files/Adapta-Eta/gtk-3.22/gtk.css
- Adapta-Nokto-Eta/README.md
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/README.md
- Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/gtk-3.22/gtk.css
- Adapta-Nokto/README.md
- Adapta-Nokto/files/Adapta-Nokto/README.md
- Adapta-Nokto/files/Adapta-Nokto/gtk-3.22/gtk.css
- Adapta/README.md
- Adapta/files/Adapta/README.md
- Adapta/files/Adapta/gtk-3.22/gtk.css
* GTK 3.22 - add a minimum height to headerbars.
Closes #565
> Adapta bugfix update 190319

- Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
- Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon_old.css
- Cinnamox-Aubergine/files/Cinnamox-Aubergine/gtk-3.20/gtk.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon_old.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/gtk-3.20/gtk.css
- Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
- Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon_old.css
- Cinnamox-Heather/files/Cinnamox-Heather/gtk-3.20/gtk.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon_old.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/gtk-3.20/gtk.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon_old.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/gtk-3.20/gtk.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon_old.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/gtk-3.20/gtk.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon_old.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/gtk-3.20/gtk.css
* Cinnamon Panel - add support for spacer applet styling  .spacer-box
* Cinnamon Panel - add support for :shade state in simple workspace switcher applet
* Cinnamon Panel - rework graph view for workspace switcher applet
* GTK3.20 - don't apply border-radius to headerbars - looks wrong with apps with split headerbars like gnome-disks.
> Cinnamox theme update 010820

- Graphite-One/files/Graphite-One/cinnamon/cinnamon.css
Remove hard coded icon size, tidy up the menus, make the thumbnail title more legible
> Graphite-One: hard coded icon size, menu tidy up, thumbnail title scale

- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/cinnamon.css
The current value of height attribute is 1.2em. This is far to small and pushes the text off the bottom of the menu. A new value of 2.8em looks perfectly fine and also matches the same value in the theme Numix-Cinnamon-Semi-Transparent. Changing this value will have no effect on versions of cinnamon prior to 4.6 as the Menu applet previously ignored this value (and set it to 30px regardless) which is probably why it was overlooked.
> Numix-Cinnamon-Transparent: Adjust height value in .menu-selected-app-box 

- Faience/files/Faience/cinnamon/cinnamon.css
This fix replaces min-height with vertical padding. It fixes an overlapping icons problem in cinnamenu's grid view.
> Faience theme: Fix display problem in cinnamenu grid view.

- Pragmatic-Darker-Blue/files/Pragmatic-Darker-Blue/cinnamon/cinnamon.css
This class is not currently used by any other applet and the background-color (red) was copied from a base theme although it was unused.
> [Pragmatic-Darker-Blue]Set reasonable color for use in cinnamenu

- Carta/files/Carta/cinnamon/cinnamon.css
Remove unnecessary border property that is causing the menu category list and menu application list to jump up and down when hovering with the mouse.
> [Carta] Fix for menu applet

- Windows-10/files/Windows-10/cinnamon/cinnamon.css
Remove fixed width property from panelLeft first-child in cinnamon.css to prevent menu applet label from being covered up by adjoining applets/icons etc.
+ Remove min-height property from .menu class which seems to serve no purpose but which does however cause a problem for cinnamenu's context menu.
> [Windows-10] Fix for menu applet label being covered up

- Faded-Dream/files/Faded-Dream/cinnamon/cinnamon.css
Class is not used by any other applet. The previous color is copied unchanged from a base theme.
> [Faded-Dream] Set color for use in cinnamenu

- Pragmatic-Darker-Blue/files/Pragmatic-Darker-Blue/gtk-3.22/gtk-dark.css
The PR adds dark theme for gtk-3.22 based on diff of dark theme for 3.0.
This fixes an issue when GTK tries to read gtk-3.0 git-dark.css theme while running gtk-3.22 related app.
The issue looks as follows (see controls and panels):
and throws a ton of errors like follows:
```console
(pitivi:21683): Gtk-WARNING **: 15:40:50.908: Theme parsing error: gtk-dark.css:3809:114: The :prelight pseudo-class is deprecated. Use :hover instead.
(pitivi:21683): Gtk-WARNING **: 15:40:50.908: Theme parsing error: gtk-dark.css:3811:78: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(pitivi:21683): Gtk-WARNING **: 15:40:50.908: Theme parsing error: gtk-dark.css:3812:72: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(pitivi:21683): Gtk-WARNING **: 15:40:50.908: …
```
> [Pragmatic-Darker-Blue] ported gtk-dark from gtk-3.0 to gtk-3.22

- Pragmatic-Darker-Blue/files/Pragmatic-Darker-Blue/gtk-3.22/gtk-dark.css
This PR fixes unreadable tooltips in GTK-3.22 dark theme for Pragmatic-Darker-Blue
> [Pragmatic-Darker-Blue] fixed GTK-3.22 tooltip font color for dark theme

- waterbody/files/waterbody/cinnamon/cinnamon.css
@tirtharajsinha This is just a suggestion, you may want to style it differently.
.menu-category-button-hover is used by Cinnamenu applet when setting "activate categories on click" is set. It's not used by any other applet at the moment.
> [Waterbody] Fix .menu-category-button-hover class for use in Cinnamenu applet.

- Adapta/files/Adapta/cinnamon/cinnamon.css
class to match hover color for app buttons and fav buttons. This class is not currently used by any other applet.
@smurphos
> [Adapta] Fix hover color in .menu-category-button-hover..

- Orchidea/files/Orchidea/cinnamon/cinnamon.css
Removing side padding so that applets on the ends of the panels can be clicked on when the mouse is in the corner. Currently if you send your mouse cursor to a corner with vigor and click, nothing happens because the side padding puts buttons on the ends of panels slightly away from the end.
Pinging @Andr35 for approval.
> [Orchidea] Remove side padding so that corners are click zones

- Orchidea/files/Orchidea/cinnamon/cinnamon.css
- Orchidea/src/sass/_common.scss
Fix some tooltip readability issues as pointed out by @fredcw 
New tooltip colors are:
> Orchidea: better tooltips

- Orchidea/files/Orchidea/cinnamon/cinnamon.css
Reducing the border-radius of .menu-application-button-selected {} to 20px still keeps the list buttons in the default menu applet fully rounded but fixes a problem in cinnamenu's grid view where the button label goes outside the highlighted area.
> [Orchidea] Fix grid button in cinnamenu

- Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
- Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon_old.css
- Cinnamox-Aubergine/files/Cinnamox-Aubergine/gtk-3.20/gtk.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon_old.css
- Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/gtk-3.20/gtk.css
- Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
- Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon_old.css
- Cinnamox-Heather/files/Cinnamox-Heather/gtk-3.20/gtk.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon_old.css
- Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/gtk-3.20/gtk.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon_old.css
- Cinnamox-Rhino/files/Cinnamox-Rhino/gtk-3.20/gtk.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon_old.css
- Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/gtk-3.20/gtk.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon_old.css
- Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/gtk-3.20/gtk.css
* Cinnamon - improved support for calendar with events applet in 5.2
* Cinnamon - added support for new run dialog selectors in 5.2
* Cinnamon - added menu-category-button-hover selector for improved cinnamenu compatibility
* GTK3.20 - improved contrast for Events in Gnome Calendar
> Cinnamox update 211221

- Windows-10/README.md
Removes opening bracket (`(`) from the themes description to allow markdown to render the link properly.
> Fix markdown syntax error

- Pragmatic-Darker-Blue/files/Pragmatic-Darker-Blue/gtk-3.22/gtk.css
This PR fixes missing coloring for GTK file chooser file name input in GTK-3.22 for Pragmatic-Darker-Blue
before:
after:
> Pragmatic-Darker-Blue: fixed missing coloring for GTK file chooser

- Carta/files/Carta/cinnamon/cinnamon.css
Thanks for this beautiful theme @andr35 !
This is a proposition for a minor improvement on the theme's usability: it was a bit annoying not being able to distinguish active apps from the others in the window bar (e.g. find which windows are open). Only the currently focused window was highlighted. 
This PR changes the theme to highlight the currently focused window in blue (reusing a color from the theme, like in slider bars), and other open windows in grey.
> Carta: Highlight active apps in the grouped window bar

- Mint-XP/info.json
Makes the cinnamon settings themes dialog unnecessarily wide when you click on the download tab.
> Mint-XP: Fix theme name being too long

- Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
- Adapta/files/Adapta/cinnamon/cinnamon.css
On Linux Mint 21.3 with Cinnamon, when the [cornerbar@cinnamon.org](https://github.com/linuxmint/cinnamon/tree/master/files/usr/share/cinnamon/applets/cornerbar%40cinnamon.org) applet is added the cornerbar is not getting displayed.
This is because the [CSS rules required for the cornerbar applet](https://github.com/linuxmint/cinnamon/blob/ca8df1fc82b8d068d72bc2b974cc1168952e4122/data/theme/cinnamon.css#L1882-L1898) are missing from the styles.
After adding the proposed styles the cornerbar looks like this:
> ![cornerbar](https://github.com/linuxmint/cinnamon-spices-themes/assets/87750369/99f1b19c-b734-48ce-881c-3957188f5898)
> Add cornerbar styles to Adapta and Adapta-Nokto themes

- Orchidea/files/Orchidea/cinnamon/cinnamon.css
> Orchidea: fix expo-workspaces-name-entry being too wide

- CBlue/CHANGELOG.md
- CBlue/files/CBlue/cinnamon/cinnamon.css
- CBlue/files/CBlue/cinnamon/theme.json
- CGreen/CHANGELOG.md
- CGreen/files/CGreen/cinnamon/cinnamon.css
- CGreen/files/CGreen/cinnamon/theme.json
Update for CBlue/CGreen themes.
> CBlue/CGreen: weather applet touch-up

- CBlue/CHANGELOG.md
- CBlue/README.md
- CBlue/files/CBlue/cinnamon/cinnamon.css
- CBlue/files/CBlue/cinnamon/theme.json
- CGreen/CHANGELOG.md
- CGreen/README.md
- CGreen/files/CGreen/cinnamon/cinnamon.css
- CGreen/files/CGreen/cinnamon/theme.json
@rcalixte: The conflict should be removed.
Regards.
> CBlue/CGreen: Improvement for Cinnamon 6.4

- Glass-Mint-Classic/README.md
- Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/cinnamon.css
- Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/theme.json
- Glass-Mint-Classic/info.json
Avoid bug: https://github.com/linuxmint/cinnamon/issues/12712
Also updated readmes little bit, didn't do it for ages.
> fix: crash on Cinnamon 6.4.6

- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/cinnamon.css
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/_OSD.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/_alt-tab.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/_modal-dialogs.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/_popup-menus.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/applets/_0-INDEX.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/applets/_app-menu.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/applets/_window-list-applets.scss
- Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/scss/main/controls/_entries.scss
Implement last two commits in scss instead of css
Add support for:
GWL icon badge, list-item, and thumbnail-menu
cinnamon 6.4 dialogs (partial)
cinnamon 6.4 media-keys-osd (partial)
window-list-preview
fixes: #848
> Numix-Cinnamon-Transparent: Update for cinnamon 6.4
