Mint-XY-Greybird-Blue/README.md
Mint-XY-Greybird-Blue/files/Mint-XY-Greybird-Blue/README.md
Mint-XY/README.md
Mint-XY/files/Mint-XY/README.md

- Fixed broken links on READMEs.

Themes updates

---

Kiss-Kool-Viper/files/Kiss-Kool-Viper/cinnamon/cinnamon.css

> i.e. restore menu function, credible applet-box spacing in vertical panel,
> and use the theme backgrounds for the OSD popups

Kiss-Kool-Viper: add basic Cinnamon 3.2 features

---

Loki/files/Loki/cinnamon/cinnamon.css

Restore intended menu function
Make OSD popup design consistent with menu theming
Make vertical panel spacing for applets sensible

Loki: basic changes to support Cinnamon 3.2

---

Vivaldi/files/Vivaldi/cinnamon/cinnamon.css

.menu
OSD themed
vertical panel applet-box

Vivaldi: add basic Cinnamon 3.2 facilities

---

Vivaldi-ZorinOS/files/Vivaldi-ZorinOS /cinnamon/cinnamon.css

.menu
applet-box.vertical
Make the OSD match the theme

Vivaldi-ZorinOS: add some Cinnamon 3.2 features

---

Serena/files/Serena/cinnamon/cinnamon.css

ensure OSD popups match the theme
ensure vertical panel applet spacing is sensible

Restore themed menu in 3.2

---

Facebook/files/Facebook/cinnamon/cinnamon.css

Ensure vertical panel spacing/placement is sensible
Fix one OSD coming up unreadable on a light background

Facebook: Restore menu theming in 3.2

---

Glass-Mint/files/Glass Mint/cinnamon/cinnamon.css

Set applet spacing in vertical panel
Suppress warning error messages in log file

Glass Mint: Restore menu theming

---

Glass-Mint-Classic/files/Glass Mint Classic/cinnamon/cinnamon.css

Set applet spacing/sizing in vertical panel
Correct warning messages

Glass Mint Classic: restore themed menu in 3.2

---

Glass-Ubuntu/files/Glass Ubuntu/cinnamon/cinnamon.css

Ensure applets sensibly spaced in vertical panels
Correct warning messages

Glass-Ubuntu: Correct theming of menu in 3.2

---

Glass-Wheezy/files/Glass Wheezy/cinnamon/cinnamon.css

Set vertical styling for applet-box
Suppress a couple of warning messages

Glass-Wheezy: Correct menu theming for 3.2

---

Glass-Wheezy-Classic/files/Glass Wheezy Classic/cinnamon/cinnamon.css

set vertical style for applet-box
Suprpess a couple of error messages

Glass-Wheezy-Classic: restore menu theming in 3.2

---

Nightlife/files/Nightlife - Violette/cinnamon/cinnamon.css

Add themed OSD
Add vertical applet-box css
Note there are variant themes in here that require further attention.

Nightlife-Violette: restore 3.2 menu theming

---

Mint-Y-Dark-Blue/files/Mint-Y-Dark-Blue/cinnamon/cinnamon.css

Add vertical css for applet-box

Mint-Y-Dark: Restore 3.2 menu theming

---

Nightlife/files/Nightlife - Flax/cinnamon/cinnamon.css
Nightlife/files/Nightlife - Graphite/cinnamon/cinnamon.css
Nightlife/files/Nightlife - Honey/cinnamon/cinnamon.css
Nightlife/files/Nightlife - Human/cinnamon/cinnamon.css
Nightlife/files/Nightlife - Mint/cinnamon/cinnamon.css
Nightlife/files/Nightlife - Rubine/cinnamon/cinnamon.css

add .vertical applet-box css
Add two new themed OSDs
Will break up into separate themes in a subsequent commit

Nightlife: variants: Restore menu theming in 3.2

---

Tyr-himinn/files/Tyr himinn/cinnamon/cinnamon.css
Tyr-jord/files/Tyr jord/cinnamon/cinnamon.css

For Tyr-jord and Tyr-himinn
This fixes linuxmint/cinnamon issue #3826

Tyr-jord, Tyr-himinn: Set width of calendar-day-heading to prevent ellipsis

---

Glass-Fedora/files/Glass Fedora/cinnamon/cinnamon.css

And add a panel background for left and right menus

Glass-Fedora: Ensure the menu theming is right in 3.2

---

New-Minty/files/New-Minty/README.md
New-Minty/files/New-Minty/cinnamon/cinnamon.css
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__f--hover.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__f--pressed.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__f.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__l--hover.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__l--pressed.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__l.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__m--hover.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__m--pressed.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-green__m.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-red__s--hover.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-red__s--pressed.svg
New-Minty/files/New-Minty/cinnamon/img/buttons/button-red__s.svg
New-Minty/files/New-Minty/cinnamon/img/containers/light-bg__first__horiz.svg
New-Minty/files/New-Minty/cinnamon/img/containers/light-bg__last__horiz.svg

Changelog at: https://github.com/germanfr/new-minty/commits/master

New-Minty update

---

Spearmint-Leaf/files/Spearmint Leaf/cinnamon/cinnamon.css

Needed outline added in order to be visible in all cases.

Spearmint Leaf: add panel highlight

---

Serena/files/Serena/cinnamon/cinnamon.css

Needed outline added in order to be visible in all cases.

Serena: add panel highlight

---

Blue-Moon/files/Blue-Moon/cinnamon/cinnamon.css
Dark-Moon/files/Dark-Moon/cinnamon/cinnamon.css

Needed outline added in order to be visible in all cases.

Blue-Moon, Dark-Moon: Add panel highlight

---

Photocopy/files/Photocopy/cinnamon/cinnamon.css

Photocopy: change desklet background to contain

---

Mint-XP-Metallic/files/Mint-XP-Metallic/cinnamon/cinnamon.css

Ensures that the highlight in the panel settings screen works OK.

Mint-XP-Metallic: add panel highlight

---

Mint-XP-Homestead/files/Mint-XP-Homestead/cinnamon/cinnamon.css

Ensures the panel settings works OK.

Mint-XP-Homestead: add panel highlight

---

Vivaldi-ZorinOS/files/Vivaldi-ZorinOS /cinnamon/cinnamon.css

also ensure flag looks right in keyboard applet

Vivaldi-ZorinOS: add panel highlight

---

README.md

Link to: https://github.com/linuxmint/Cinnamon/tree/master/data/theme added...

Link to Cinnamon/data/theme in ReadMe added

---

Tyr-himinn/files/Tyr himinn/cinnamon/cinnamon.css

also correct some vertical panel alignment issues

Tyr-himinn: adapt for Cinnamon 3.4

---

Tyr-jord/files/Tyr jord/cinnamon/cinnamon.css

also correct some problems in vertical panel alignments

Tyr-jord: update for cinnamon 3.4

---

Graphite-Zero/files/Graphite-Zero/cinnamon/cinnamon.css

and remove some unwanted bounce on hover

Graphite-zero: Correct menu text shadow bug

---

Eleganse-dark/files/Eleganse-dark/cinnamon/cinnamon.css

Margin issue (https://forums.linuxmint.com/viewtopic.php?f=90&t=248787&p=1337024#p1337024) fixed, Minor design change.

Update for margin issue occurred in cinnamon 3.4.3

---

Eleganse/files/Eleganse/cinnamon/cinnamon.css

Margin issue on cinnamon 3.4.3 fixed. Thank you @brownsr :-)

 Margin issue fixed

---

Glass-Fedora-Classic/files/Glass-Fedora-Classic/cinnamon/cinnamon.css
Glass-Fedora-Classic/files/Glass-Fedora-Classic/cinnamon/theme.json
Glass-Fedora/files/Glass-Fedora/cinnamon/cinnamon.css
Glass-Fedora/files/Glass-Fedora/cinnamon/theme.json
Glass-Glaucous-Classic/files/Glass-Glaucous-Classic/cinnamon/cinnamon.css
Glass-Glaucous-Classic/files/Glass-Glaucous-Classic/cinnamon/theme.json
Glass-Glaucous/files/Glass-Glaucous/cinnamon/cinnamon.css
Glass-Glaucous/files/Glass-Glaucous/cinnamon/theme.json
Glass-Lemon-Classic/files/Glass-Lemon-Classic/cinnamon/cinnamon.css
Glass-Lemon-Classic/files/Glass-Lemon-Classic/cinnamon/theme.json
Glass-Lemon/files/Glass-Lemon/cinnamon/cinnamon.css
Glass-Lemon/files/Glass-Lemon/cinnamon/theme.json
Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/cinnamon.css
Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/theme.json
Glass-Mint/files/Glass-Mint/cinnamon/cinnamon.css
Glass-Mint/files/Glass-Mint/cinnamon/theme.json
Glass-Ubuntu-Classic/files/Glass-Ubuntu-Classic/cinnamon/cinnamon.css
Glass-Ubuntu-Classic/files/Glass-Ubuntu-Classic/cinnamon/theme.json
Glass-Ubuntu/files/Glass-Ubuntu/cinnamon/cinnamon.css
Glass-Ubuntu/files/Glass-Ubuntu/cinnamon/theme.json

Version upgraded to 2.2
Code cleaned.
Remade main menu, popup menu items.
Corrected run dialog, sound player window.
Added some description translations to English.
Corrected script for updating version numbers.

Glass Themes: Version upgraded to 2.2

---

Eleganse-dark/files/Eleganse-dark/cinnamon/cinnamon.css

Visual consistency across window list and other applets

Eleganse-Dark: Visual consistency improvement

---

Metallic_Cyan/files/Metallic_Cyan/cinnamon/cinnamon.css

Removed borders, reduced padding size to 6px & font size to 10pt

Metallic cyan1.1

---

Serena/info.json
Silk/info.json
Vivaldi-ZorinOS/info.json
Vivaldi/info.json

[Brahim = freemangilgamesh](https://github.com/linuxmint/cinnamon-spices-themes/issues/221#issuecomment-324312564)
fyi @freemangilgamesh

4 Brahim themes: use author GitHub name

---

Eleganse-dark/files/Eleganse-dark/cinnamon/cinnamon.css

* Panel shadow reduced
* Menu scrollBar size reduced
* run-dialog visual consistency improvement

Eleganse-dark: Visual consistency improvements

---

Void/files/Void/cinnamon/cinnamon.css

This is an attempt to fix #195.
**IMPORTANT:** I've hacked my way through to this fix. I have no idea about side effects. I tried my best to find useful documentation on theming but failed. So if anyone finds a better fix I'd be glad to improve the PR.

Issue #195 Void - Fix keyboard icon hover width

---

Serena/info.json
Silk/info.json
Vivaldi-ZorinOS/info.json
Vivaldi/info.json

Themes by @freemangilgamesh

---

BelaLugosi/README.md
BelaLugosi/info.json
Photocopy/README.md
Photocopy/info.json

Themes by @brownsr

---

Ambiance-Crunchy/README.md
Ambiance-Crunchy/info.json

Ambiance-Crunchy: Cleanup info.json

---

Escarlata/info.json

Escarlata: Cleanup info.json

---

aque/info.json

aque: Cleanup info.json

---

Thunderbolt/info.json
Tomcat/README.md
Tomcat/info.json

Clean up info.json files
@Radek71

Themes by @Radek71

---

Carta/info.json

Carta: Cleanup info.json

---

ChromeOS/info.json
Windows-10/README.md
Windows-10/info.json

Themes by @Elbullazul

---

Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/gtk-2.0/gtkrc
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/gtk-2.0/gtkrc.hidpi
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/gtk-3.0/gtk.css
Cinnamox-Gold-Spice/info.json
Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/gtk-2.0/gtkrc
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/gtk-2.0/gtkrc.hidpi
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/gtk-3.0/gtk.css
Cinnamox-Kashmir-Blue/info.json
Cinnamox-Rhino/README.md
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
Cinnamox-Rhino/files/Cinnamox-Rhino/gtk-2.0/gtkrc
Cinnamox-Rhino/files/Cinnamox-Rhino/gtk-2.0/gtkrc.hidpi
Cinnamox-Rhino/files/Cinnamox-Rhino/gtk-3.0/gtk.css
Cinnamox-Rhino/info.json
Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/gtk-2.0/gtkrc.hidpi
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/gtk-3.0/gtk.css
Cinnamox-Willow-Grove/info.json

Updating all Cinnamox themes to support .progress theming for 3.6. Tweaks to Panel, Window List and Panel launchers. Updated GTKe themes to add some gradients too elements. Optional HDPI version of GTK2

Cinnamox Update

---

Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/info.json
Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/info.json
Cinnamox-Rhino/README.md
Cinnamox-Rhino/info.json
Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/info.json

Sorry, some bad spelling and grammar in the updated info.json and README.md on the last commit.

Cinnamox Themes - Fix typos in info.json and README.md - sorry!

---

ScaleUp/README.md
ScaleUp/files/ScaleUp/cinnamon/cinnamon.css
ScaleUp/info.json

ScaleUp: eliminate fixed fonts, for uniform response to font scaling

---

New-Minty/files/New-Minty/cinnamon/cinnamon.css

Changelog at: https://github.com/germanfr/new-minty/commits/master

Update New-Minty (with joined menus)

---

Faience/files/Faience/cinnamon/cinnamon.css

also add some menu border and margin to improve conspicuity

Faience: update for cinnamon 3.8

---

Kiss-Kool-Viper/files/Kiss-Kool-Viper/cinnamon/cinnamon.css

and sort out some vertical panel issues

Kiss-Kool-Viper: update for Cinnamon 3.8

---

Blue-Moon/files/Blue-Moon/cinnamon/cinnamon.css

the ability to theme the window-list-preview works well in an in-your-face theme like this

Blue-moon: update for Cinnamon 3.8

---

Eleganse/files/Eleganse/cinnamon/cinnamon.css

Eleganse: add missing tooltip CSS

---

Glass-Fedora-Classic/files/Glass-Fedora-Classic/cinnamon/cinnamon.css
Glass-Fedora-Classic/files/Glass-Fedora-Classic/cinnamon/theme.json
Glass-Fedora/files/Glass-Fedora/cinnamon/cinnamon.css
Glass-Fedora/files/Glass-Fedora/cinnamon/theme.json
Glass-Glaucous-Classic/files/Glass-Glaucous-Classic/cinnamon/cinnamon.css
Glass-Glaucous-Classic/files/Glass-Glaucous-Classic/cinnamon/theme.json
Glass-Glaucous/files/Glass-Glaucous/cinnamon/cinnamon.css
Glass-Glaucous/files/Glass-Glaucous/cinnamon/theme.json
Glass-Lemon-Classic/files/Glass-Lemon-Classic/cinnamon/cinnamon.css
Glass-Lemon-Classic/files/Glass-Lemon-Classic/cinnamon/theme.json
Glass-Lemon/files/Glass-Lemon/cinnamon/cinnamon.css
Glass-Lemon/files/Glass-Lemon/cinnamon/theme.json
Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/cinnamon.css
Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/theme.json
Glass-Mint/files/Glass-Mint/cinnamon/cinnamon.css
Glass-Mint/files/Glass-Mint/cinnamon/theme.json
Glass-Ubuntu-Classic/files/Glass-Ubuntu-Classic/cinnamon/cinnamon.css
Glass-Ubuntu-Classic/files/Glass-Ubuntu-Classic/cinnamon/theme.json
Glass-Ubuntu/files/Glass-Ubuntu/cinnamon/cinnamon.css
Glass-Ubuntu/files/Glass-Ubuntu/cinnamon/theme.json

Glass Themes: little transparency updates for windowlist, workspace-add-button, workspace-caption, window-close-area.

Glass Themes: little transparency updates

---

Void/files/Void/cinnamon/cinnamon.css

Fix #400 & #111  amongst other things. This is a quick fix so may review in more detail again.
* Reformat indentation
* Removed deprecated styes
* Fixed notification and sound player buttons
* Added widows-list-item:progress
* Added #panel:highlight
* Fixed dnd colors
* Added .about
* Added .tile-hud

Void theme Quick Fix

---

Baldr/files/Baldr/LICENSE
Baldr/info.json
Faience/files/Faience/LICENSE
Faience/info.json
Loki/files/Loki/LICENSE
Loki/info.json
Tyr-himinn/files/Tyr-himinn/LICENSE
Tyr-himinn/info.json
Tyr-jord/files/Tyr-jord/LICENSE
Tyr-jord/info.json

He agreed to use GPLv3, see #402.

Add license for @bimsebasse themes

---

Cinnamox-Aubergine/files/Cinnamox-Aubergine/info.json
Cinnamox-Aubergine/info.json
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/info.json
Cinnamox-Gold-Spice/info.json
Cinnamox-Heather/files/Cinnamox-Heather/info.json
Cinnamox-Heather/info.json
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/info.json
Cinnamox-Kashmir-Blue/info.json
Cinnamox-Rhino/files/Cinnamox-Rhino/info.json
Cinnamox-Rhino/info.json
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/info.json
Cinnamox-Rosso-Cursa/info.json
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/info.json
Cinnamox-Willow-Grove/info.json
Cinnamox-Zanah/files/Cinnamox-Zanah/info.json
Cinnamox-Zanah/info.json

Cinnamox themes - add license to info.json

---

Ambiance-Minty/info.json

I'm pretty sure it was GPL3 under its original ownership, but it is licenseless otherwise.

Add License Value

---

Jade-1/files/Jade-1/assets/unmaxPress.svg
Jade-1/files/Jade-1/cinnamon/cinnamon.css
Jade-1/files/Jade-1/gtk-3.0/gtk.css
Jade-1/files/Jade-1/gtk-3.22/apps/cinnamon-applications.css
Jade-1/files/Jade-1/gtk-3.22/gtk.css
Jade-1/files/Jade-1/metacity-1/button_backdrop.svg
Jade-1/files/Jade-1/metacity-1/button_close.svg
Jade-1/files/Jade-1/metacity-1/button_close_hover.svg
Jade-1/files/Jade-1/metacity-1/button_maximize.svg
Jade-1/files/Jade-1/metacity-1/button_maximize_hover.svg
Jade-1/files/Jade-1/metacity-1/button_menu.svg
Jade-1/files/Jade-1/metacity-1/button_menu_prelight.svg
Jade-1/files/Jade-1/metacity-1/button_menu_pressed.svg
Jade-1/files/Jade-1/metacity-1/button_minimize.svg
Jade-1/files/Jade-1/metacity-1/button_minimize_hover.svg
Jade-1/files/Jade-1/metacity-1/button_shade.svg
Jade-1/files/Jade-1/metacity-1/button_shade_prelight.svg
Jade-1/files/Jade-1/metacity-1/button_shade_pressed.svg
Jade-1/files/Jade-1/metacity-1/button_unmaximize.svg
Jade-1/files/Jade-1/metacity-1/button_unmaximize_hover.svg
Jade-1/files/Jade-1/metacity-1/button_unshade.svg
Jade-1/files/Jade-1/metacity-1/button_unshade_prelight.svg
Jade-1/files/Jade-1/metacity-1/button_unshade_pressed.svg
Jade-1/files/Jade-1/metacity-1/metacity-theme-1.xml
Jade-1/files/Jade-1/metacity-1/metacity-theme-3.xml

* cinnamon 3.8 updates
* added metacity-3
* bugfixing gtk and cinnamon colors

cinnamon 3.8 updates, metacity-3, bugfixes

---

Discreet-Flat/README.md
Discreet-Flat/files/Discreet-Flat/cinnamon/cinnamon.css
Discreet-Flat/src/about_dialog.styl
Discreet-Flat/src/applets/calendar.styl
Discreet-Flat/src/applets/index.styl
Discreet-Flat/src/applets/menu.styl
Discreet-Flat/src/applets/notifications.styl
Discreet-Flat/src/applets/on-screen_keyboard.styl
Discreet-Flat/src/applets/panel_launcher.styl
Discreet-Flat/src/applets/sound.styl
Discreet-Flat/src/applets/window_list.styl
Discreet-Flat/src/applets/workspace_switcher.styl
Discreet-Flat/src/buttons.styl
Discreet-Flat/src/cinnamon.styl
Discreet-Flat/src/colors.styl
Discreet-Flat/src/common.styl
Discreet-Flat/src/desklets/clock.styl
Discreet-Flat/src/desklets/index.styl
Discreet-Flat/src/looking_glass.styl
Discreet-Flat/src/magnifier.styl
Discreet-Flat/src/modal_dialogs.styl
Discreet-Flat/src/notifications.styl
Discreet-Flat/src/overview.styl
Discreet-Flat/src/overview_corner.styl
Discreet-Flat/src/panel.styl
Discreet-Flat/src/preview_window.styl
Discreet-Flat/src/run_dialog.styl
Discreet-Flat/src/workspace_osd.styl

From the changelog:
- Added support for Cinnamon 3.6's progress indicator
- Updated for Cinnamon 3.8
With this update I am also moving the code I previously hosted [here](https://github.com/getkey/discreet-flat) before this repo existed, and which is now impractical.
Since I am using a preprocessor, I put the source files in `src/` as discussed in #232.

Discreet Flat: Update to v1.1.4

---

Adapta-Eta/README.md
Adapta-Nokto-Eta/README.md
Adapta-Nokto/README.md

Just fixing a typo in the readme instructions. Thanks @sethbergman for spotting it.

Adapta variants readme fix

---

Cinnamox-Aubergine/README.md
Cinnamox-Aubergine/files/Cinnamox-Aubergine/README.md
Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
Cinnamox-Heather/README.md
Cinnamox-Heather/files/Cinnamox-Heather/README.md
Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
Cinnamox-Rhino/README.md
Cinnamox-Rhino/files/Cinnamox-Rhino/README.md
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
Cinnamox-Rosso-Cursa/README.md
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/README.md
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css

* Cinnamon - new style-classes for Cinnamon 4.0 stock menu.
* Cinnamon - initial support for Cinnamon 4.0 grouped-window-list applet.
* Cinnamon - fixed workspace-switcher applet simple mode display on vertical panels.

Cinnamox themes - initial Cinnamon 4.0 support

---

Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css

* Cinnamon - added support for new windows overview style classes in Cinnamon 4.0
* Cinnamon - adjusted panel item padding and margin scheme to better support user adjustable icon sizes in  Cinnamon 4.0 and avoid issues with GWL on vertical panels.
* Cinnamon - re-themed GWL to distinguish better distinguish focussed apps in both icon and icon+label views.

Cinnamox - windows overview and panel fixes for Cinnamon 4 & GWL

---

Adapta-Eta/README.md
Adapta-Eta/files/Adapta-Eta/README.md
Adapta-Eta/files/Adapta-Eta/cinnamon/cinnamon.css
Adapta-Nokto-Eta/README.md
Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/README.md
Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/cinnamon/cinnamon.css
Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/README.md
Adapta/files/Adapta/README.md
Adapta/files/Adapta/cinnamon/cinnamon.css

* Cinnamon - revert most changes to menu theming from #470
* Cinnamon - retain fixes to menu-search width and Cinnamenu right-click context menu
* Cinnamon - added support for menu-systembuttons-box and -top-box in case new stock menu design is revived
* Cinnamon - added support for new style-classes for Cinnamon 4.0 overview
* Cinnamon - GWL applet  - simplified highlighting scheme to match Adapta upstream highlighting for ITM.

Adapta - further improvements for Cinnamon 4.0

---

Adapta-Eta/files/Adapta-Eta/cinnamon/cinnamon.css
Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/cinnamon/cinnamon.css
Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/files/Adapta/cinnamon/cinnamon.css

* Cinnamon - remove a duplicated style-class
* Cinnamon - fix a bug in GWL pseudo-class styling

Adapta - bugfix update

---

Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css

Cinnamon - amend panel item highlighting scheme to minimise use of transparent borders.
Cinnamon - fix icon placement for ITM
Cinnamon - Cinnamon 4 - GWL - better badge theming

Cinnamox - 181118 update

---

Vivaldi/files/Vivaldi/cinnamon/cinnamon.css

@freemangilgamesh As this is a popular theme I've got some suggested changes to update this for Cinnamon 4.0, so it's ready for people to use when Mint 19.1 stable comes out.  If you are happy please say, if you want to make your own changes please send a PR through.  If I don't hear back I will assume you are not active anymore and push this PR in a few days.
Regards
Simon

Vivaldi: update for Cinnamon 4.0

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json

Thanks for smurphos.
I hope the modification is not too dirty.
[screenshot](https://user-images.githubusercontent.com/29017677/50204568-3656a280-035d-11e9-8c35-ddd008926c5e.png)

CBlue: Fix bug Grouped Window List Applet for panel left/right

---

Spider-Void/files/Spider-Void/cinnamon/cinnamon.css

Update cinnamon.css: make visible all days in calendar

---

Graphite-One/files/Graphite-One/cinnamon/cinnamon.css

Graphite-Zero: remove text shadow from menu-selected-app-box

---

BelaLugosi/files/BelaLugosi/cinnamon/cinnamon.css
Graphite-One/files/Graphite-One/cinnamon/cinnamon.css
Graphite-Zero/files/Graphite-Zero/cinnamon/cinnamon.css
Photocopy/files/Photocopy/cinnamon/cinnamon.css
SimpleDock/files/SimpleDock/cinnamon/cinnamon.css

minimise use of blur in box-shadow

---

Tyr-himinn/files/Tyr-himinn/cinnamon/cinnamon.css
Tyr-jord/files/Tyr-jord/cinnamon/cinnamon.css

Removed the search icon's shadows, it didn't look good in my opinion
The user "Almijr" here said too, with screenshot
https://cinnamon-spices.linuxmint.com/themes/view/Tyr-jord#comments

Tyr-yord, Tyr-himmin: Removed search icon shadow

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/common-assets/menu/button-menu-hover-bottom.svg
CBlue/files/CBlue/cinnamon/common-assets/menu/button-menu-hover-left.svg
CBlue/files/CBlue/cinnamon/common-assets/menu/button-menu-hover-right.svg
CBlue/files/CBlue/cinnamon/common-assets/menu/button-menu-hover-top.svg
CBlue/files/CBlue/cinnamon/common-assets/misc/add-workspace-hover.svg
CBlue/files/CBlue/cinnamon/common-assets/panel/window-list-hover-bottom.svg
CBlue/files/CBlue/cinnamon/common-assets/panel/window-list-hover-left.svg
CBlue/files/CBlue/cinnamon/common-assets/panel/window-list-hover-right.svg
CBlue/files/CBlue/cinnamon/common-assets/panel/window-list-hover-top.svg
CBlue/files/CBlue/cinnamon/theme.json

Some adjustments to the CBlue theme.

CBlue: update

---

Adapta-Eta/README.md
Adapta-Eta/files/Adapta-Eta/README.md
Adapta-Eta/files/Adapta-Eta/cinnamon/cinnamon.css
Adapta-Nokto-Eta/README.md
Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/README.md
Adapta-Nokto-Eta/files/Adapta-Nokto-Eta/cinnamon/cinnamon.css
Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/README.md
Adapta/files/Adapta/README.md
Adapta/files/Adapta/cinnamon/cinnamon.css

* Cinnamon - amend panel label text alignment to support centred labels on multiline calendar applet labels
* Cinnamon - Simplified Grouped Window List thumbnail theming in preparation for Cinnamon 4.2

Adapta themes update 060619

---

Graphite-One/files/Graphite-One/cinnamon/cinnamon.css
Graphite-Zero/files/Graphite-Zero/cinnamon/cinnamon.css

Introduce the characteristic border, remove transparency

graphite-zone/one: theme notifications better

---

Discreet-Flat/README.md
Discreet-Flat/files/Discreet-Flat/cinnamon/cinnamon.css
Discreet-Flat/src/applets/notifications.styl

Fix invisible sound bar

---

CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/common-assets/misc/message.svg
CGreen/files/CGreen/cinnamon/theme.json

Hi,
Can I do only one PR for the two themes (CBlue, CGreen) or do I have to separate them as I did?
Thank you.

CGreen: update

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/common-assets/misc/message.svg
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/theme.json

Additions for Firefox 69 and a modification of the.svg file in CBlue.

Update readme: Cblue, CGreen

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CBlue/info.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json
CGreen/info.json

Update: CBlue, CGreen

---

Divo/files/Divo/cinnamon/cinnamon.css

fixes #608    Border colour is not changed but the gradient of the active window is increased so contrast should increase a little

Divo: increase gradient for active windows in window list

---

Baldr/files/Baldr/cinnamon/cinnamon.css

Also correct an OSD where the contrast made it virtually illegible, also remove the no longer required 'about' CSS

Baldr: allow font scaling

---

CBlue/README.md
CGreen/README.md

Modification of the README to make the Firefox extra work.

Update README for Firefox 75

---

Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/README.md
Adapta/files/Adapta/README.md
Adapta/files/Adapta/cinnamon/cinnamon.css

* Cinnamon - alt-tab window preview mode - shade backdrop so the previewed window pops
* Cinnamon - virtual keyboard - usability tweaks

Adapta themes update 26052020

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CBlue/files/CBlue/cinnamon/userChrome.css
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json
CGreen/files/CGreen/cinnamon/userChrome.css

Hi,
Update for CBlue and CGreen themes.
Regards.

OSD, panel editing and userChrome.css update

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
update for CBlue and CGreen themes.
Regards.

editing the grouped-window-list applet.

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
update for CBlue and CGreen.
Regards.

thumbnail outline (window list preview) and overview retouching (Ctl+Alt+Down).

---

Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/cinnamon.css
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/compile
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/scss/main/applets/_1-applet-globals.scss
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/scss/main/applets/_app-menu.scss
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/scss/third-party__applets/_0-INDEX.scss
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/scss/third-party__applets/_cinnamenu.scss
Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/theme.json

fixed some issues with cinnamenu and double line applet like time and 
date one

[Numix-Semi-Transparent-Theme] minor fix

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is an update for CBlue and CGreen themes.
Regards.

Touching up the weather applet and the slider bar.

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is an update for CBlue and CGreen themes.
Regards.

Non-work-day calendar in bold.

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
Deletion of a variable that became useless after the update of the weather applet v: 2.6.8.
Regards.

deleted a variable following the update of the weather applet.

---

CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is an update for CBlue and CGreen themes.
Regards.

2.0: corrected the calendar applet and removed obsolete codes

---

Tyr-himinn/files/Tyr-himinn/cinnamon/cinnamon.css

... different sized icons in menu applet.

[Tyr-himinn] Swap height for padding to allow for

---

Baldr/files/Baldr/cinnamon/cinnamon.css

Swap height for padding to allow for different icon sizes in menu applet.

[Baldr] Swap height for padding to allow for different icon sizes in menu applet.

---

CBlue/CHANGELOG.md
CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is update for CBlue and CGreen themes.
Regards.

CBlue, CGreen: tooltip shadow, visual indicator Lock/Num and special vowel characters of the virtual keyboard.

---

Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css

menu-category-button-hover class is not currently used by any other applet.
@smurphos

[Adapta-Nokto] Fix hover color for use in cinnamenu applet

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/TimeFull
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/TimeFull
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

A small update of the themes.
Regards.

Update themes CBlue and CGreen.

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/TimeFull
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/TimeFull
CGreen/files/CGreen/cinnamon/theme.json

Conky update ( flickering correction...) for CBlue and CGreen themes.
Regards.

Conky update.

---

Faded-Dream/info.json

Update author name in info.json to match new github account name

Update info.json in Faded-Dream

---

Cinnamox-Aubergine/README.md
Cinnamox-Aubergine/files/Cinnamox-Aubergine/README.md
Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon.css
Cinnamox-Aubergine/files/Cinnamox-Aubergine/cinnamon/cinnamon_old.css
Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/README.md
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon.css
Cinnamox-Gold-Spice/files/Cinnamox-Gold-Spice/cinnamon/cinnamon_old.css
Cinnamox-Heather/README.md
Cinnamox-Heather/files/Cinnamox-Heather/README.md
Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon.css
Cinnamox-Heather/files/Cinnamox-Heather/cinnamon/cinnamon_old.css
Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/README.md
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon.css
Cinnamox-Kashmir-Blue/files/Cinnamox-Kashmir-Blue/cinnamon/cinnamon_old.css
Cinnamox-Rhino/README.md
Cinnamox-Rhino/files/Cinnamox-Rhino/README.md
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon.css
Cinnamox-Rhino/files/Cinnamox-Rhino/cinnamon/cinnamon_old.css
Cinnamox-Rosso-Cursa/README.md
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/README.md
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon.css
Cinnamox-Rosso-Cursa/files/Cinnamox-Rosso-Cursa/cinnamon/cinnamon_old.css
Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/README.md
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon.css
Cinnamox-Willow-Grove/files/Cinnamox-Willow-Grove/cinnamon/cinnamon_old.css

Hello, been a while - hope all is well!

Cinnamox - Support for Events in 5.2+ Calendar Applet

---

Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/README.md
Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/README.md
Adapta/files/Adapta/README.md
Adapta/files/Adapta/cinnamon/cinnamon.css

* Cinnamon - support for Spacer applet theming added in Cinnamon 4.2
* Cinnamon - workspace switcher applet - better distinguish empty workspaces in simple button mode.
* Cinnamon - minor tweak to pop-up menu sizes to better match GTK menus
* Cinnamon - incorporate @fredcw patch to menu category hover color for Cinnamenu
* Cinnamon - add support for calendar with events in Cinnamon 5.2
* Cinnamon - support for new Run Dialog theming in Cinnamon 5.2

Adapta update 211221

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/TimeFull
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/TimeFull
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
a litle modification for a better visibility of non-work days in calendar.
Regards.

Update for CBlue and CGreen themes

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/common-assets/misc/message.svg
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/common-assets/misc/message.svg
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is an update for CBlue and CGreen themes.
Regards.

Theme update: modification of the calendar (Cinnamon 5.2) and notifications

---

Orchidea/files/Orchidea/cinnamon/cinnamon.css
Orchidea/src/sass/_common.scss

Fix some issues with the grouped window list and the window thumbnails.
Details are in issue #741
Closes #741

[Orchidea] fix grouped window list issues

---

Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/cinnamon.css
Glass-Mint-Classic/files/Glass-Mint-Classic/cinnamon/theme.json

Too late update for Cinnamon from previous Linux Mint =)
Stylized calendar widget, fixes for player widget, workspace overview.
Updated hints.

[Glass-Mint-Clasic] Update for Cinnamon 5.2

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Update CBlue/CGreen themes.
Regards.

Update for Bundy01's themes

---

New-Minty/files/New-Minty/cinnamon/cinnamon.css

New-Minty: Remove line limiting cinnamon menu applet height

---

Numix-Cinnamon-Semi-Transparent/files/Numix-Cinnamon-Semi-Transparent/cinnamon/cinnamon.css
Numix-Cinnamon-Transparent/files/Numix-Cinnamon-Transparent/cinnamon/cinnamon.css

Numix Cinnamon Transparent/Semi-transparent: Prevent limiting of menu applet height

---

CBlue/README.md
CGreen/README.md

New wallpaper, add Plank's theme and minor calendar touch-up + panel

---

CBlue/CHANGELOG.md
CBlue/README.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/common-assets/misc/message.svg
CBlue/files/CBlue/cinnamon/dock.theme
CBlue/files/CBlue/cinnamon/menu.svg
CBlue/files/CBlue/cinnamon/theme.json
CBlue/files/CBlue/cinnamon/userChrome.css
CBlue/info.json
CGreen/CHANGELOG.md
CGreen/README.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/common-assets/misc/message.svg
CGreen/files/CGreen/cinnamon/dock.theme
CGreen/files/CGreen/cinnamon/menu.svg
CGreen/files/CGreen/cinnamon/theme.json
CGreen/files/CGreen/cinnamon/userChrome.css
CGreen/info.json

Hi,
update for CBlue and CGreen themes.
Regards.

CBlue/CGreen: fixed two small bugs + modifications to calendar/notifications and Plank theme

---

Adapta-Nokto/files/Adapta-Nokto/cinnamon/cinnamon.css
Adapta/files/Adapta/cinnamon/cinnamon.css

fixes: #762
This can probably be merged fairly quickly as @smurphos hasn't been active on github for more than a year.

Adapta themes: fix sound applet media controls padding

---

CPurple/README.md
CPurple/color palette

I forgot how markdown format worked.

fix formatting error in README.md

---

Qogir-Light/files/Qogir-Light/cinnamon/cinnamon.css

Fixes: https://github.com/linuxmint/cinnamon/issues/12126

[Qogir Light] fix menu text dpi bug

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
this is an update for CBlue/CGreen themes.
Regards.

CBlue/CGreen: Fixed a display bug in workspace names.

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

Hi,
an update for CBlue/CGreen themes.
Regards.

CBlue/CGreen: font size increased

---

Chillies/files/Chillies/cinnamon/cinnamon.css
Fraiche/files/Fraiche/cinnamon/cinnamon.css
Pepper/files/Pepper/cinnamon/cinnamon.css

changed color and added shadow to .calendar-today-home-button, other small color changes.

minor calendar text visibility fixes

---

Orchidea/files/Orchidea/cinnamon/cinnamon.css
Orchidea/src/sass/_common.scss

Now, active applications in window list are highlighted with a light grey circle.
Also, number in application badge is more visible.
fixes #830

Orchidea: fix grouped-window-list-item-box active issue

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/cinnamon.css
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/cinnamon.css
CGreen/files/CGreen/cinnamon/theme.json

CBlue/CGreen: Fix issue #837

---

CBlue/CHANGELOG.md
CBlue/files/CBlue/cinnamon/common-assets/switch/switch-off.svg
CBlue/files/CBlue/cinnamon/common-assets/switch/switch-on.svg
CBlue/files/CBlue/cinnamon/theme.json
CGreen/CHANGELOG.md
CGreen/files/CGreen/cinnamon/common-assets/switch/switch-off.svg
CGreen/files/CGreen/cinnamon/common-assets/switch/switch-on.svg
CGreen/files/CGreen/cinnamon/theme.json

Hi,
a small update to modernise the switch buttons for CBlue/CGreen themes.
Regards.

CBlue/CGreen: switch button touch-up
